[project]
name = "common_venv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "imageio>=2.37.0",
    "jupyter>=1.1.1",
    "librosa>=0.11.0",
    "nltk>=3.9.1",
    "notebook>=7.4.4",
    "pandas>=2.3.0",
    "pillow>=11.3.0",
    "pyarrow>=22.0.0",
    "pyspark>=4.0.1",
    "python-frontmatter>=1.1.0",
    "scikit-learn>=1.7.0",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.5",
    "tensorboard>=2.19.0",
    "torch>=2.7.1",
    "torchvision>=0.22.1",
    "tqdm>=4.67.1",
]
